CREATE TABLE image (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    image_url VARCHAR(255) NOT NULL,
    caption TEXT,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    user_id BIGINT NOT NULL
);

ALTER TABLE image ADD CONSTRAINT fk_images_on_account FOREIGN KEY (user_id) REFERENCES account (id);
CREATE INDEX idx_image_user_id ON image(user_id);