CREATE TABLE user_likes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    user_id BIGINT NOT NULL,
    image_id BIGINT NOT NULL
);

ALTER TABLE user_likes ADD CONSTRAINT fk_likes_on_account FOREIGN KEY (user_id) REFERENCES account (id);
-- fix primary key for image
ALTER TABLE image ADD CONSTRAINT pk_image PRIMARY KEY (id);
ALTER TABLE user_likes ADD CONSTRAINT fk_likes_on_image FOREIGN KEY (image_id) REFERENCES image (id);
CREATE INDEX idx_likes_image_id ON user_likes(image_id);