CREATE TABLE user_follows (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    user_id BIGINT NOT NULL,
    follower_id BIGINT NOT NULL
);

ALTER TABLE user_follows ADD CONSTRAINT fk_follows_on_user FOREIGN KEY (user_id) REFERENCES account (id);
ALTER TABLE user_follows ADD CONSTRAINT fk_follows_on_follower FOREIGN KEY (follower_id) REFERENCES account (id);
CREATE INDEX idx_follows_user_id ON user_follows(user_id);
CREATE INDEX idx_follows_follower_id ON user_follows(follower_id);
