CREATE TABLE profile (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    description TEXT,
    avatar BOOLEAN NOT NULL DEFAULT FALSE,
    user_id BIGINT NOT NULL,
    CONSTRAINT pk_profile PRIMARY KEY (id)
);

ALTER TABLE profile ADD CONSTRAINT fk_profile_on_account FOREIGN KEY (user_id) REFERENCES account (id);

-- fix primary key for follows and likes
ALTER TABLE user_likes ADD CONSTRAINT pk_like PRIMARY KEY (id);
ALTER TABLE user_follows ADD CONSTRAINT pk_follow PRIMARY KEY (id);
