CREATE TABLE user_comments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    content TEXT,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    author_id BIGINT NOT NULL,
    image_id BIGINT NOT NULL,
    CONSTRAINT pk_comment PRIMARY KEY (id)
);

ALTER TABLE user_comments ADD CONSTRAINT fk_comment_on_account FOREIGN KEY (author_id) REFERENCES account (id);
CREATE INDEX idx_comments_image_id ON user_comments(image_id);
