CREATE TABLE messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    sender_id BIGINT NOT NULL,
    receiver_id BIGINT NOT NULL,
    content TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    is_read BOOLEAN DEFAULT FALSE,
    CONSTRAINT pk_message PRIMARY KEY (id)
);

ALTER TABLE messages ADD CONSTRAINT fk_message_on_sender FOREIGN KEY (sender_id) REFERENCES account (id);
ALTER TABLE messages ADD CONSTRAINT fk_message_on_receiver FOREIGN KEY (receiver_id) REFERENCES account (id);
