version: '3.3'

services:
  main:
    build: 
      context: ./main/
      dockerfile: Dockerfile
    container_name: image_main
    depends_on:
      dbimg:
        condition: service_healthy
    expose:
      - 8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://dbimg:5432/img_dev
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - FRONTEND_URL=http://localhost:8000
  dbimg:
    image: 'postgres:13.1-alpine'
    container_name: dbimg
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=img_dev
    expose:
      - 5432
    healthcheck:
      test: ['CMD', 'psql', '-U', 'admin', 'img_dev', '-c', 'SELECT 1']
      interval: 10s
      timeout: 5s
      retries: 5
    command:
      - "postgres"
      - "-c"
      - "wal_level=logical"
  frontend:
    container_name: image_frontend
    build: 
      context: ./frontend/
      dockerfile: Dockerfile
    depends_on:
      - main
    ports:
      - "8000:80"
    environment:
      - API_URL=main
      - API_PORT=8080
    command: /bin/sh -c "envsubst '$${API_URL} $${API_PORT}' < /etc/nginx/nginx.conf.template > /etc/nginx/nginx.conf && nginx -g 'daemon off;'"
  rabbitmq:
    image: rabbitmq:3.11-management-alpine
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: rabbit
      RABBITMQ_DEFAULT_PASS: password
      RABBITMQ_DEFAULT_VHOST: /
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3
  cdc:
    build: 
      context: ./cdc/embedded/images-cdc/
      dockerfile: Dockerfile
    container_name: image_cdc
    depends_on:
      dbimg:
        condition: service_healthy
      cassandra:
        condition: service_healthy
      cassandra-init:
        condition: service_completed_successfully
    expose:
      - 8080
    ports:
      - "8081:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=rabbit
      - SPRING_CASSANDRA_CONTACTPOINTS=cassandra
      - SPRING_CASSANDRA_PORT=9042
      - SPRING_DATA_CASSANDRA_USERNAME=admin
      - SPRING_DATA_CASSANDRA_PASSWORD=admin
      - SPRING_CASSANDRA_LOCAL-DATACENTER=datacenter1
      - SPRING_CASSANDRA_KEYSPACE-NAME=images_cassandra
  cassandra:
    image: cassandra:latest
    container_name: cassandra-container
    ports:
      - "9042:9042"
    environment:
      - CASSANDRA_USER=admin
      - CASSANDRA_PASSWORD=admin
    healthcheck:
      test: ["CMD-SHELL", "[ $$(nodetool statusgossip) = running ]"]
      interval: 10s
      timeout: 5s
      retries: 50
  cassandra-init:
    image: cassandra:latest
    depends_on:
        cassandra:
          condition: service_healthy
    restart: "no"
    entrypoint: ["/usr/bin/bash", "-e", "/init.sh"]
    volumes:
      - ./cdc/embedded/cassandra-config/init.sh:/init.sh:z
  logs:
    container_name: image_logs
    build: 
      context: ./cdc/embedded/images-logs
      dockerfile: Dockerfile
    depends_on:
      - cdc
    ports:
      - "8001:80"
  rabbit-init:
    image: alpine/curl:latest
    depends_on:
        rabbitmq:
          condition: service_healthy
    restart: "no"
    entrypoint: ["sh", "-e", "/init.sh"]
    volumes:
      - ./cdc/rabbit/init.sh:/init.sh:z

  debezium:
    image: debezium/server:2.4
    container_name: debezium-server
    ports:
      - 8082:8080
    volumes:
      - ./cdc/rabbit/conf:/debezium/conf:z
    depends_on:
      rabbitmq:
        condition: service_healthy
      dbimg:
        condition: service_healthy
      rabbit-init:
        condition: service_completed_successfully
 
  integration:
    build: 
      context: ./cdc/rabbit/integration
      dockerfile: Dockerfile
    container_name: image_integration
    depends_on:
      rabbitmq:
        condition: service_healthy
      rabbit-init:
        condition: service_completed_successfully
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PASSWORD=password
      - SPRING_RABBITMQ_USERNAME=rabbit
