name: Angular CI
run-name: building frontend
on: [push]
jobs:
  Build-Frontend:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Frontend build triggered by ${{ github.event_name }} event."
      - name: Checkout the source code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Install dependencies
        working-directory: ./frontend
        run: npm ci
      - name: Run tests
        working-directory: ./frontend
        run: npm run test:ci
      - name: Build
        working-directory: ./frontend
        run: npm run build 
